### PR TITLE
add option to hide track.

### PR DESCRIPTION
**Pull request by siong1987**
screen shot 2014-11-29 at 3 01 42 pm

### CODE REVIEW

**Comment by yannickl** [comment]
Sorry for the late, thank you.

**Comment by tbechtum** [comment]
Hi Yannick,

thank you very much for your work.

At the moment I am very busy but I will integrate your last version as soon as possible.

Many greetings,
Thomas

P.S: Mon solidarité avec tous les français et Charly Hebdo.

On 06 Jan 2015, at 22:34, Yannick Loriot <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the late, thank you.

**Comment by yannickl** [comment]
You're welcome.

P.S: Thank you!

**Comment by tbechtum** [comment]
Hi Yannick,

I tested the YLProgressBar 3.5.1 release and it meets our requirements.

Thanks again for your work,
my best wishes,
Thomas

Begin forwarded message:

Date: 6 Jan 2015 22:34:15 CET

**Pull request merged**
